version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    depends_on:
      - mysql
      - redis
    networks:
      - himmah-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: myhimm
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: laravel
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - himmah-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - himmah-network

volumes:
  mysql_data:

networks:
  himmah-network:
    driver: bridge

