<?php

namespace App\Http\Controllers;

use App\Models\Lesson;
use App\Services\VideoService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class VideoStreamController extends Controller
{
    protected $videoService;

    public function __construct(VideoService $videoService)
    {
        $this->videoService = $videoService;
    }

    /**
     * Get Signed URL for HLS Master Playlist
     */
    public function getStreamUrl(Lesson $lesson)
    {
        if (!$lesson->canUserAccess(Auth::user())) {
            return response()->json(['error' => 'Unauthorized'], 403);
        }

        // If HLS is ready (completed) use the HLS master playlist; otherwise
        // allow a fallback to a directly uploaded private video file (e.g. MP4)
        // This preserves content protection because we still return a short-lived
        // signed URL generated by VideoService. We only allow the fallback when
        // a direct `video_path` exists on the lesson record.

        $url = null;
        if ($lesson->processing_status === 'completed' && !empty($lesson->hls_path)) {
            // Generate Signed URL for master.m3u8
            $url = $this->videoService->getWasabiSignedUrl($lesson->hls_path, 10);
        } elseif (!empty($lesson->video_path)) {
            // Fallback: signed URL for directly uploaded private file (MP4)
            $url = $this->videoService->getWasabiSignedUrl($lesson->video_path, 10);
        } else {
            return response()->json(['error' => 'Video is still processing'], 422);
        }

        return response()->json([
            'stream_url' => $url,
            'watermark' => [
                'text' => Auth::user()->email,
                'id' => Auth::user()->id
            ]
        ]);
    }

    /**
     * Proxy for HLS Segments (Optional but recommended for higher security)
     * This ensures segments are also signed or validated
     */
    public function getSegment(Request $request, $lessonId, $quality, $filename)
    {
        $lesson = Lesson::findOrFail($lessonId);
        if (!$lesson->canUserAccess(Auth::user())) {
            abort(403);
        }

        $path = "hls/{$lessonId}/{$quality}/{$filename}";
        return redirect($this->videoService->getWasabiSignedUrl($path, 5));
    }
}
